name: Protocol Buffers
on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

jobs:
  main:
    name: Protocol Buffers
    runs-on: ubuntu-latest

    steps:
      - name: Install tools
        run: go get -u -v github.com/yoheimuta/protolint/cmd/protolint

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint
        run: protolint lint ./protos
